GLOBAL_DEFS := -DCY_USE_PSVP=0 -Dtviibh8m -DCYT4BF8CDE -DHYPER_RAM=1

LDSCRIPT := flm/initonly_linker_script.ld

INCLPATHS := \
-Isdl/common								\
-Isdl/common/hdr							\
-Isdl/common/hdr/cmsis						\
-Isdl/common/hdr/cmsis/include				\
-Isdl/common/src							\
-Isdl/common/src/drivers					\
-Isdl/common/src/drivers/adc				\
-Isdl/common/src/drivers/canfd				\
-Isdl/common/src/drivers/crypto				\
-Isdl/common/src/drivers/crypto/src			\
-Isdl/common/src/drivers/dma				\
-Isdl/common/src/drivers/evtgen				\
-Isdl/common/src/drivers/gpio				\
-Isdl/common/src/drivers/ipc				\
-Isdl/common/src/drivers/lin				\
-Isdl/common/src/drivers/lvd				\
-Isdl/common/src/drivers/mcwdt				\
-Isdl/common/src/drivers/mpu				\
-Isdl/common/src/drivers/prot				\
-Isdl/common/src/drivers/scb				\
-Isdl/common/src/drivers/smartio			\
-Isdl/common/src/drivers/sysflt				\
-Isdl/common/src/drivers/sysint				\
-Isdl/common/src/drivers/syslib				\
-Isdl/common/src/drivers/syspm				\
-Isdl/common/src/drivers/sysreset			\
-Isdl/common/src/drivers/sysrtc				\
-Isdl/common/src/drivers/systick			\
-Isdl/common/src/drivers/syswdt				\
-Isdl/common/src/drivers/tcpwm				\
-Isdl/common/src/drivers/trigmux			\
-Isdl/common/src/mw							\
-Isdl/common/src/mw/button					\
-Isdl/common/src/mw/semihosting				\
-Isdl/common/src/mw/sw_timer				\
-Isdl/common/src/startup					\
-Isdl/tviibh8m								\
-Isdl/tviibh8m/hdr							\
-Isdl/tviibh8m/hdr/rev_b					\
-Isdl/tviibh8m/hdr/rev_b/ip				\
-Isdl/tviibh8m/hdr/rev_b/mcureg			\
-Isdl/tviibh8m/src							\
-Isdl/tviibh8m/src/drivers					\
-Isdl/tviibh8m/src/drivers/audioss			\
-Isdl/tviibh8m/src/drivers/cpu				\
-Isdl/tviibh8m/src/drivers/crypto			\
-Isdl/tviibh8m/src/drivers/crypto/libs		\
-Isdl/tviibh8m/src/drivers/ethernet		\
-Isdl/tviibh8m/src/drivers/flash			\
-Isdl/tviibh8m/src/drivers/flexray			\
-Isdl/tviibh8m/src/drivers/flexray/api		\
-Isdl/tviibh8m/src/drivers/flexray/ccal	\
-Isdl/tviibh8m/src/drivers/flexray/fhal	\
-Isdl/tviibh8m/src/drivers/sd_host			\
-Isdl/tviibh8m/src/drivers/smif			\
-Isdl/tviibh8m/src/drivers/sysclk			\
-Isdl/tviibh8m/src/drivers/sysflt			\
-Isdl/tviibh8m/src/drivers/sysreg			\
-Isdl/tviibh8m/src/examples/smif			\
-Isdl/tviibh8m/src/interrupts				\
-Isdl/tviibh8m/src/interrupts/rev_b		\
-Isdl/tviibh8m/src/mw						\
-Isdl/tviibh8m/src/mw/reghc				\
-Isdl/tviibh8m/src/mw/smif_mem				\
-Isdl/tviibh8m/src/system					\
-Isdl/tviibh8m/src/system/rev_b			\


