/***************************************************************************//**
* \file cyreg_prot.h
*
* \brief
* PROT register definition header
*
* \note
* Generator version: 1.4.0.1226
* Database revision: TVIIBH8M_CFR_METALTO
*
********************************************************************************
* \copyright
* Copyright 2016-2018, Cypress Semiconductor Corporation. All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
*******************************************************************************/

#ifndef _CYREG_PROT_H_
#define _CYREG_PROT_H_

#include "cyip_prot.h"

/**
  * \brief SMPU structure (PROT_SMPU_SMPU_STRUCT0)
  */
#define CYREG_PROT_SMPU_SMPU_STRUCT0_ADDR0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR0_t*) 0x40232000UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT0_ATT0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT0_t*) 0x40232004UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT0_ADDR1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR1_t*) 0x40232020UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT0_ATT1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT1_t*) 0x40232024UL)

/**
  * \brief SMPU structure (PROT_SMPU_SMPU_STRUCT1)
  */
#define CYREG_PROT_SMPU_SMPU_STRUCT1_ADDR0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR0_t*) 0x40232040UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT1_ATT0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT0_t*) 0x40232044UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT1_ADDR1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR1_t*) 0x40232060UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT1_ATT1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT1_t*) 0x40232064UL)

/**
  * \brief SMPU structure (PROT_SMPU_SMPU_STRUCT2)
  */
#define CYREG_PROT_SMPU_SMPU_STRUCT2_ADDR0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR0_t*) 0x40232080UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT2_ATT0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT0_t*) 0x40232084UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT2_ADDR1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR1_t*) 0x402320A0UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT2_ATT1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT1_t*) 0x402320A4UL)

/**
  * \brief SMPU structure (PROT_SMPU_SMPU_STRUCT3)
  */
#define CYREG_PROT_SMPU_SMPU_STRUCT3_ADDR0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR0_t*) 0x402320C0UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT3_ATT0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT0_t*) 0x402320C4UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT3_ADDR1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR1_t*) 0x402320E0UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT3_ATT1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT1_t*) 0x402320E4UL)

/**
  * \brief SMPU structure (PROT_SMPU_SMPU_STRUCT4)
  */
#define CYREG_PROT_SMPU_SMPU_STRUCT4_ADDR0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR0_t*) 0x40232100UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT4_ATT0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT0_t*) 0x40232104UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT4_ADDR1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR1_t*) 0x40232120UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT4_ATT1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT1_t*) 0x40232124UL)

/**
  * \brief SMPU structure (PROT_SMPU_SMPU_STRUCT5)
  */
#define CYREG_PROT_SMPU_SMPU_STRUCT5_ADDR0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR0_t*) 0x40232140UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT5_ATT0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT0_t*) 0x40232144UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT5_ADDR1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR1_t*) 0x40232160UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT5_ATT1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT1_t*) 0x40232164UL)

/**
  * \brief SMPU structure (PROT_SMPU_SMPU_STRUCT6)
  */
#define CYREG_PROT_SMPU_SMPU_STRUCT6_ADDR0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR0_t*) 0x40232180UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT6_ATT0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT0_t*) 0x40232184UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT6_ADDR1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR1_t*) 0x402321A0UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT6_ATT1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT1_t*) 0x402321A4UL)

/**
  * \brief SMPU structure (PROT_SMPU_SMPU_STRUCT7)
  */
#define CYREG_PROT_SMPU_SMPU_STRUCT7_ADDR0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR0_t*) 0x402321C0UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT7_ATT0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT0_t*) 0x402321C4UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT7_ADDR1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR1_t*) 0x402321E0UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT7_ATT1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT1_t*) 0x402321E4UL)

/**
  * \brief SMPU structure (PROT_SMPU_SMPU_STRUCT8)
  */
#define CYREG_PROT_SMPU_SMPU_STRUCT8_ADDR0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR0_t*) 0x40232200UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT8_ATT0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT0_t*) 0x40232204UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT8_ADDR1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR1_t*) 0x40232220UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT8_ATT1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT1_t*) 0x40232224UL)

/**
  * \brief SMPU structure (PROT_SMPU_SMPU_STRUCT9)
  */
#define CYREG_PROT_SMPU_SMPU_STRUCT9_ADDR0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR0_t*) 0x40232240UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT9_ATT0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT0_t*) 0x40232244UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT9_ADDR1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR1_t*) 0x40232260UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT9_ATT1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT1_t*) 0x40232264UL)

/**
  * \brief SMPU structure (PROT_SMPU_SMPU_STRUCT10)
  */
#define CYREG_PROT_SMPU_SMPU_STRUCT10_ADDR0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR0_t*) 0x40232280UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT10_ATT0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT0_t*) 0x40232284UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT10_ADDR1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR1_t*) 0x402322A0UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT10_ATT1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT1_t*) 0x402322A4UL)

/**
  * \brief SMPU structure (PROT_SMPU_SMPU_STRUCT11)
  */
#define CYREG_PROT_SMPU_SMPU_STRUCT11_ADDR0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR0_t*) 0x402322C0UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT11_ATT0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT0_t*) 0x402322C4UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT11_ADDR1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR1_t*) 0x402322E0UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT11_ATT1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT1_t*) 0x402322E4UL)

/**
  * \brief SMPU structure (PROT_SMPU_SMPU_STRUCT12)
  */
#define CYREG_PROT_SMPU_SMPU_STRUCT12_ADDR0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR0_t*) 0x40232300UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT12_ATT0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT0_t*) 0x40232304UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT12_ADDR1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR1_t*) 0x40232320UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT12_ATT1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT1_t*) 0x40232324UL)

/**
  * \brief SMPU structure (PROT_SMPU_SMPU_STRUCT13)
  */
#define CYREG_PROT_SMPU_SMPU_STRUCT13_ADDR0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR0_t*) 0x40232340UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT13_ATT0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT0_t*) 0x40232344UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT13_ADDR1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR1_t*) 0x40232360UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT13_ATT1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT1_t*) 0x40232364UL)

/**
  * \brief SMPU structure (PROT_SMPU_SMPU_STRUCT14)
  */
#define CYREG_PROT_SMPU_SMPU_STRUCT14_ADDR0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR0_t*) 0x40232380UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT14_ATT0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT0_t*) 0x40232384UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT14_ADDR1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR1_t*) 0x402323A0UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT14_ATT1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT1_t*) 0x402323A4UL)

/**
  * \brief SMPU structure (PROT_SMPU_SMPU_STRUCT15)
  */
#define CYREG_PROT_SMPU_SMPU_STRUCT15_ADDR0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR0_t*) 0x402323C0UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT15_ATT0 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT0_t*) 0x402323C4UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT15_ADDR1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ADDR1_t*) 0x402323E0UL)
#define CYREG_PROT_SMPU_SMPU_STRUCT15_ATT1 ((volatile un_PROT_SMPU_SMPU_STRUCT_ATT1_t*) 0x402323E4UL)

/**
  * \brief SMPU (PROT_SMPU0)
  */
#define CYREG_PROT_SMPU_MS0_CTL         ((volatile un_PROT_SMPU_MS0_CTL_t*) 0x40230000UL)
#define CYREG_PROT_SMPU_MS1_CTL         ((volatile un_PROT_SMPU_MS1_CTL_t*) 0x40230004UL)
#define CYREG_PROT_SMPU_MS2_CTL         ((volatile un_PROT_SMPU_MS2_CTL_t*) 0x40230008UL)
#define CYREG_PROT_SMPU_MS3_CTL         ((volatile un_PROT_SMPU_MS3_CTL_t*) 0x4023000CUL)
#define CYREG_PROT_SMPU_MS4_CTL         ((volatile un_PROT_SMPU_MS4_CTL_t*) 0x40230010UL)
#define CYREG_PROT_SMPU_MS5_CTL         ((volatile un_PROT_SMPU_MS5_CTL_t*) 0x40230014UL)
#define CYREG_PROT_SMPU_MS9_CTL         ((volatile un_PROT_SMPU_MS9_CTL_t*) 0x40230024UL)
#define CYREG_PROT_SMPU_MS10_CTL        ((volatile un_PROT_SMPU_MS10_CTL_t*) 0x40230028UL)
#define CYREG_PROT_SMPU_MS13_CTL        ((volatile un_PROT_SMPU_MS13_CTL_t*) 0x40230034UL)
#define CYREG_PROT_SMPU_MS14_CTL        ((volatile un_PROT_SMPU_MS14_CTL_t*) 0x40230038UL)
#define CYREG_PROT_SMPU_MS15_CTL        ((volatile un_PROT_SMPU_MS15_CTL_t*) 0x4023003CUL)

/**
  * \brief MPU (PROT_MPU0)
  */
#define CYREG_PROT_MPU0_MS_CTL          ((volatile un_PROT_MPU_MS_CTL_t*) 0x40234000UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT0)
  */
#define CYREG_PROT_MPU5_MPU_STRUCT0_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x40235600UL)
#define CYREG_PROT_MPU5_MPU_STRUCT0_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x40235604UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT1)
  */
#define CYREG_PROT_MPU5_MPU_STRUCT1_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x40235620UL)
#define CYREG_PROT_MPU5_MPU_STRUCT1_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x40235624UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT2)
  */
#define CYREG_PROT_MPU5_MPU_STRUCT2_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x40235640UL)
#define CYREG_PROT_MPU5_MPU_STRUCT2_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x40235644UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT3)
  */
#define CYREG_PROT_MPU5_MPU_STRUCT3_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x40235660UL)
#define CYREG_PROT_MPU5_MPU_STRUCT3_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x40235664UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT4)
  */
#define CYREG_PROT_MPU5_MPU_STRUCT4_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x40235680UL)
#define CYREG_PROT_MPU5_MPU_STRUCT4_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x40235684UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT5)
  */
#define CYREG_PROT_MPU5_MPU_STRUCT5_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x402356A0UL)
#define CYREG_PROT_MPU5_MPU_STRUCT5_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x402356A4UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT6)
  */
#define CYREG_PROT_MPU5_MPU_STRUCT6_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x402356C0UL)
#define CYREG_PROT_MPU5_MPU_STRUCT6_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x402356C4UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT7)
  */
#define CYREG_PROT_MPU5_MPU_STRUCT7_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x402356E0UL)
#define CYREG_PROT_MPU5_MPU_STRUCT7_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x402356E4UL)

/**
  * \brief MPU (PROT_MPU5)
  */
#define CYREG_PROT_MPU5_MS_CTL          ((volatile un_PROT_MPU_MS_CTL_t*) 0x40235400UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT0)
  */
#define CYREG_PROT_MPU9_MPU_STRUCT0_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x40236600UL)
#define CYREG_PROT_MPU9_MPU_STRUCT0_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x40236604UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT1)
  */
#define CYREG_PROT_MPU9_MPU_STRUCT1_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x40236620UL)
#define CYREG_PROT_MPU9_MPU_STRUCT1_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x40236624UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT2)
  */
#define CYREG_PROT_MPU9_MPU_STRUCT2_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x40236640UL)
#define CYREG_PROT_MPU9_MPU_STRUCT2_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x40236644UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT3)
  */
#define CYREG_PROT_MPU9_MPU_STRUCT3_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x40236660UL)
#define CYREG_PROT_MPU9_MPU_STRUCT3_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x40236664UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT4)
  */
#define CYREG_PROT_MPU9_MPU_STRUCT4_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x40236680UL)
#define CYREG_PROT_MPU9_MPU_STRUCT4_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x40236684UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT5)
  */
#define CYREG_PROT_MPU9_MPU_STRUCT5_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x402366A0UL)
#define CYREG_PROT_MPU9_MPU_STRUCT5_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x402366A4UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT6)
  */
#define CYREG_PROT_MPU9_MPU_STRUCT6_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x402366C0UL)
#define CYREG_PROT_MPU9_MPU_STRUCT6_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x402366C4UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT7)
  */
#define CYREG_PROT_MPU9_MPU_STRUCT7_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x402366E0UL)
#define CYREG_PROT_MPU9_MPU_STRUCT7_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x402366E4UL)

/**
  * \brief MPU (PROT_MPU9)
  */
#define CYREG_PROT_MPU9_MS_CTL          ((volatile un_PROT_MPU_MS_CTL_t*) 0x40236400UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT0)
  */
#define CYREG_PROT_MPU10_MPU_STRUCT0_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x40236A00UL)
#define CYREG_PROT_MPU10_MPU_STRUCT0_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x40236A04UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT1)
  */
#define CYREG_PROT_MPU10_MPU_STRUCT1_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x40236A20UL)
#define CYREG_PROT_MPU10_MPU_STRUCT1_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x40236A24UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT2)
  */
#define CYREG_PROT_MPU10_MPU_STRUCT2_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x40236A40UL)
#define CYREG_PROT_MPU10_MPU_STRUCT2_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x40236A44UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT3)
  */
#define CYREG_PROT_MPU10_MPU_STRUCT3_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x40236A60UL)
#define CYREG_PROT_MPU10_MPU_STRUCT3_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x40236A64UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT4)
  */
#define CYREG_PROT_MPU10_MPU_STRUCT4_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x40236A80UL)
#define CYREG_PROT_MPU10_MPU_STRUCT4_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x40236A84UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT5)
  */
#define CYREG_PROT_MPU10_MPU_STRUCT5_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x40236AA0UL)
#define CYREG_PROT_MPU10_MPU_STRUCT5_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x40236AA4UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT6)
  */
#define CYREG_PROT_MPU10_MPU_STRUCT6_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x40236AC0UL)
#define CYREG_PROT_MPU10_MPU_STRUCT6_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x40236AC4UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT7)
  */
#define CYREG_PROT_MPU10_MPU_STRUCT7_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x40236AE0UL)
#define CYREG_PROT_MPU10_MPU_STRUCT7_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x40236AE4UL)

/**
  * \brief MPU (PROT_MPU10)
  */
#define CYREG_PROT_MPU10_MS_CTL         ((volatile un_PROT_MPU_MS_CTL_t*) 0x40236800UL)

/**
  * \brief MPU (PROT_MPU13)
  */
#define CYREG_PROT_MPU13_MS_CTL         ((volatile un_PROT_MPU_MS_CTL_t*) 0x40237400UL)

/**
  * \brief MPU (PROT_MPU14)
  */
#define CYREG_PROT_MPU14_MS_CTL         ((volatile un_PROT_MPU_MS_CTL_t*) 0x40237800UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT0)
  */
#define CYREG_PROT_MPU15_MPU_STRUCT0_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x40237E00UL)
#define CYREG_PROT_MPU15_MPU_STRUCT0_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x40237E04UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT1)
  */
#define CYREG_PROT_MPU15_MPU_STRUCT1_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x40237E20UL)
#define CYREG_PROT_MPU15_MPU_STRUCT1_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x40237E24UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT2)
  */
#define CYREG_PROT_MPU15_MPU_STRUCT2_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x40237E40UL)
#define CYREG_PROT_MPU15_MPU_STRUCT2_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x40237E44UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT3)
  */
#define CYREG_PROT_MPU15_MPU_STRUCT3_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x40237E60UL)
#define CYREG_PROT_MPU15_MPU_STRUCT3_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x40237E64UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT4)
  */
#define CYREG_PROT_MPU15_MPU_STRUCT4_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x40237E80UL)
#define CYREG_PROT_MPU15_MPU_STRUCT4_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x40237E84UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT5)
  */
#define CYREG_PROT_MPU15_MPU_STRUCT5_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x40237EA0UL)
#define CYREG_PROT_MPU15_MPU_STRUCT5_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x40237EA4UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT6)
  */
#define CYREG_PROT_MPU15_MPU_STRUCT6_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x40237EC0UL)
#define CYREG_PROT_MPU15_MPU_STRUCT6_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x40237EC4UL)

/**
  * \brief MPU structure (PROT_MPU_MPU_STRUCT7)
  */
#define CYREG_PROT_MPU15_MPU_STRUCT7_ADDR ((volatile un_PROT_MPU_MPU_STRUCT_ADDR_t*) 0x40237EE0UL)
#define CYREG_PROT_MPU15_MPU_STRUCT7_ATT ((volatile un_PROT_MPU_MPU_STRUCT_ATT_t*) 0x40237EE4UL)

/**
  * \brief MPU (PROT_MPU15)
  */
#define CYREG_PROT_MPU15_MS_CTL         ((volatile un_PROT_MPU_MS_CTL_t*) 0x40237C00UL)

#endif /* _CYREG_PROT_H_ */


/* [] END OF FILE */
